stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src\get_data.py
      - src\load_data.py
      - dataset/Sleephealth.csv
    outs:
      - data/raw/Sleephealth.csv
      - label_encoder/Gender_LabelEncoder.joblib
      - label_encoder/Occupation_LabelEncoder.joblib
      - label_encoder/BMI_Category_LabelEncoder.joblib
      - label_encoder/Sleep_Disorder_LabelEncoder.joblib
      - label_encoder/label_map.json

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/Sleephealth.csv
    outs:
      - data/processed/train_sleephealth.csv
      - data/processed/test_sleephealth.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
      - data/processed/train_sleephealth.csv
      - data/processed/test_sleephealth.csv
      - src/train_and_evaluate.py
    params:
      - estimators.DecisionTreeClassifier.params.criterion
      - estimators.DecisionTreeClassifier.params.max_depth
    metrics:
      - reports/scores.json:
          cache: false
      - reports/params.json:
          cache: false
    outs:
      - models/model.joblib
      - reports/figures/confusion_matrix.jpg