stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src\get_data.py
      - src\load_data.py
      - dataset/Sleephealth.csv
    outs:
      - data/raw/Sleephealth.csv
      - label_encoder/Gender_LabelEncoder.joblib
      - label_encoder/Occupation_LabelEncoder.joblib
      - label_encoder/BMI_Category_LabelEncoder.joblib
      - label_encoder/Sleep_Disorder_LabelEncoder.joblib
      - label_encoder/label_map.json

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/Sleephealth.csv
    outs:
      - data/processed/train_sleephealth.csv
      - data/processed/test_sleephealth.csv

