base:
  project: sleephealthanalysis-project
  random_state: 42
  target_col: Sleep_Disorder

data_source:
  data_source_path: dataset/Sleephealth.csv

load_data:
  raw_dataset_csv: data/raw/Sleephealth.csv
  label_encoded_data: label_encoder

split_data:
  train_path: data/processed/train_sleephealth.csv
  test_path: data/processed/test_sleephealth.csv
  test_size: 0.2