channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=23.3.1
- pip:
  - mlflow==2.5.0
  - cloudpickle==2.2.1
  - numpy==1.26.2
  - psutil==5.9.6
  - scikit-learn==1.3.0
  - scipy==1.11.4
name: mlflow-env
